# /AIAgentServer/docker-compose.yml

version: '3'

services:

  app:
    image: xagent-server:0.1
    build:
      context: ..
      dockerfile: ./XAgentServer/dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default
    container_name: XAgent-Server  

networks:
  default:
    driver: bridge
